#!/bin/bash
set -euo pipefail
# normally this is a good idea, but in this case it messes with $BE_NICE
#IFS=$'\n\t'
########################################################################
# 2015-02-23 Christopher Hirschmann c.hirschmann@jonaspasche.com
# 2018-04-16 Bernhard Ehlers be@bernhard-ehlers.de
# 2020-02-01 Florian Eckert
########################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
#
# This script will look for a system user's primary maildir
# $HOME/Maildir and possible vMailMgr maildirs under $HOME/users/
# and search them for folders indicating a certain setup:
#
# \
#  \___ Inbox
#   \
#    \___ 0 Spamfilter
#     \
#      \___ als Ham lernen
#      |
#      |___ als Spam lernen
#
# If it finds this folder structure in any maildir, it will show
# files from the folders 'als Ham lernen' and 'als Spam lernen' to CRM114
# (so it can learn) and after that it will delete them.
#
# You can make this script more verbose with '-v'.
#
# You can also test this script with '-n' in dry run mode. If combined
# with '-v' it will output what it would have done, but won't do any-
# thing.
#
########################################################################

DRYRUN=0;
VERBOSE=0;

HAMDIR=".0 Spamfilter.als Ham lernen"
SPAMDIR=".0 Spamfilter.als Spam lernen"
TRASHDIR=".Trash"
SPAMFILTER="$HOME/crm114/crm114 -u $HOME/crm114 mailreaver.crm --"

MAILSIZELIMITkb=3915;  
CACHEWORKAROUND=1;    # Choose between 1 and 2
                      # Mails for learning being larger than setted $MAILSIZELIMITkb will be...
                      #           1: ...deleted without showing them to CRM114
                      #           2: ...truncated to the $MAILSIZELIMIT and will be shown to CRM114 (not yet confirmed to be 100% working)
MOVEHAMBACKTOINBOXAFTERLEARNING=0;

while getopts ":hvn" Option
do
    case $Option in
        h       )       echo -e "Usage:\n-n\tdry run\n-v\tbe verbose\n-h\tthis help message"; exit 0;;
        n       )       DRYRUN=1; ;;
        v       )       VERBOSE=1; ;;       
        *       )       echo -e "ERROR: Unimplemented option chosen: -${OPTARG}"; exit 1;;
    esac
done

if `grep -q "CentOS release 5" /etc/redhat-release`;
then
    # ionice -c3 is not supported on CentOS 5 for users != root (needs Linux => 2.6.25)
    # so let's fall back to ionice -c2 -n7 which is better than nothing
    BE_NICE="nice -n 19 ionice -c2 -n7";
else
    BE_NICE="nice -n 19 ionice -c3";
fi

if [ "${DRYRUN}" == "1" ];
then
    echo "Running in dry run mode."
fi

# to be able to process directory and file names regardless of any kind
# of weird characters we need to list these names separated by null
# characters and process them accordingly.

( find ${HOME} -mindepth 1 -maxdepth 1 -type d -name Maildir -print0 ; if [ -d ${HOME}/users ]; then find ${HOME}/users/ -mindepth 1 -maxdepth 1 -type d -print0 ; fi )| while read -d $'\0' -r DIR ;
do
    if [ "${VERBOSE}" == "1" ];
    then
        echo "Looking for mails in ${DIR}.";
    fi
    if [ -d "${DIR}/${SPAMDIR}" ];
    then
        for SUBDIR in new cur ;
        do
            find "${DIR}/${SPAMDIR}/${SUBDIR}" -type f -print0 | while read -d $'\0' -r spammail ;
            do
                [ -z "${spammail##*:2,*T*}" ] && continue
                if [ "${VERBOSE}" == "1" ];
                then
                    echo -e "\tEating spam now: \"${spammail}\"";
                fi
                if [ "${DRYRUN}" == "0" ];
                then
                    thismailsizekb=$(( $(wc -c <"${spammail}") / 1024 )) # size of this mail in kb
                    if [ "${VERBOSE}" == "1" ]
                    then
                        echo -e "\tSize of the mail: ${thismailsizekb}kb";
                    fi
                    
                    if [ $thismailsizekb -ge $MAILSIZELIMITkb ] && [ "${CACHEWORKAROUND}" == "2" ];    # if size of mail is greater or equal than maxmailsizelimit
                    then
                        echo -e "\tMail is larger than setted limit. Workaround 2 is active. Will truncate the mailfile to setted limit of ${MAILSIZELIMITkb}kb";
                        truncate -s "${MAILSIZELIMITkb}K" "${spammail}"  # truncate the mail to the mailsizelimit
                        if [ "${VERBOSE}" == "1" ];
                        then
                            echo -e "\tSuccessfully truncated the mail to ${MAILSIZELIMITkb}kb.";
                        fi
                    fi
                    
                    if [ $thismailsizekb -lt $MAILSIZELIMITkb ] || [ "${CACHEWORKAROUND}" == "2" ];
                    then
                        echo -e "\tI will show the mail to CRM114 now...";
                        ${BE_NICE} ${SPAMFILTER} --spam < "${spammail}" > /dev/null;
                        if [ "${VERBOSE}" == "1" ];
                        then
                            echo -e "\tSuccessfully showed the mail to CRM114 as Spam.";
                        fi
                    fi
                    
                    if [ $thismailsizekb -ge $MAILSIZELIMITkb ] && [ "${CACHEWORKAROUND}" == "1" ] && [ "${VERBOSE}" == "1" ];
                    then
                        echo -e "\tMail is larger than setted limit. Workaround 1 is active. Will not show this mail to CRM114.";
                    fi
                    
                    rm -f "${spammail}";
                    if [ "${VERBOSE}" == "1" ];
                    then
                        echo -e "\tMail was deleted from spamfolder.";
                    fi
                fi
            done
        done
    fi
    if [ -d "${DIR}/${HAMDIR}" ];
    then
        for SUBDIR in new cur ;
        do
            find "${DIR}/${HAMDIR}/${SUBDIR}" -type f -print0 | while read -d $'\0' -r hammail ;
            do
                [ -z "${hammail##*:2,*T*}" ] && continue
                if [ "${VERBOSE}" == "1" ];
                then
                    echo -e "Eating ham now: \"${hammail}\"";
                fi
                if [ "${DRYRUN}" == "0" ];
                then
                    thismailsizekb=$(( $(wc -c <"${hammail}") / 1024 )) # size of this mail in kb
                    if [ "${VERBOSE}" == "1" ]
                    then
                        echo -e "\tSize of the mail: ${thismailsizekb}kb";
                    fi
                  
                    if [ "${MOVEHAMBACKTOINBOXAFTERLEARNING}" == "1" ];
                    then
                        cp -p "${hammail}" "${DIR}/cur";
                        if [ "${VERBOSE}" == "1" ];
                        then
                            echo -e "\tMail was copied \"back\" to Inbox.";
                        fi
                    fi                  
                  
                    if [ $thismailsizekb -ge $MAILSIZELIMITkb ] && [ "${CACHEWORKAROUND}" == "2" ];    # if size of mail is greater or equal than maxmailsizelimit
                    then
                        echo -e "\tMail is larger than setted limit. Workaround 2 is active. Will truncate the mailfile to setted limit of ${MAILSIZELIMITkb}kb";
                        truncate -s "${MAILSIZELIMITkb}K" "${hammail}"  # truncate the mail to the mailsizelimit
                        if [ "${VERBOSE}" == "1" ];
                        then
                            echo -e "\tSuccessfully truncated the mail to ${MAILSIZELIMITkb}kb.";
                        fi
                    fi
                    
                    if [ $thismailsizekb -lt $MAILSIZELIMITkb ] || [ "${CACHEWORKAROUND}" == "2" ];
                    then
                        echo -e "\tI will show the mail to CRM114 now...";
                        mailfilter=`mktemp -t mailfilter.XXXXXXXX`
                        ${BE_NICE} ${SPAMFILTER} --good < "${hammail}" | maildrop "${mailfilter}";
                        if [ "${VERBOSE}" == "1" ];
                        then
                            echo -e "\tSuccessfully showed the mail to CRM114 as Ham.";
                        fi
                        rm -f "${mailfilter}"
                        if [ "${VERBOSE}" == "1" ];
                        then
                            echo -e "\tRemoved ${mailfilter}";
                        fi
                    fi
                    
                    if [ $thismailsizekb -ge $MAILSIZELIMITkb ] && [ "${CACHEWORKAROUND}" == "1" ] && [ "${VERBOSE}" == "1" ];
                    then
                        echo -e "\tMail is larger than setted limit. Workaround 1 is active. Will not show this mail to CRM114.";
                    fi
                    
                    rm -f "${hammail}";
                    if [ "${VERBOSE}" == "1" ];
                    then
                        echo -e "\tMail was deleted from hamfolder.";
                    fi
                fi
            done
        done
    fi
done

if [ "${VERBOSE}" == "1" ];
then
    echo "Done looking for mails.";
fi
